Add groups users api
LT-Students/ScheduleService pull request #4
Opened 2023-12-17 15:54 UTC by HidirovMarat

2023-12-17 16:00 UTC, VLiamin commented on src/ScheduleService.Models.Dto/Responses/GroupUser/UpdateGroupUserResponse.cs
> +namespace LT.DigitalOffice.ScheduleService.Models.Dto.Responses.GroupUser;
empty line

2023-12-17 16:00 UTC, VLiamin commented on src/ScheduleService.Models.Dto/Requests/GroupUser/UpdateGroupUserRequest.cs
> +  public string Op {  get; set; }
Are you sure?

2023-12-17 16:00 UTC, VLiamin commented on src/ScheduleService/Controllers/GroupsUsersController.cs
> +      [FromServices] IEditGroupUserCommand command,
4 spaces instead of 2

2023-12-18 23:18 UTC, SolovyovDmitry requested changes
Follow the same advices as in previous one

2024-01-18 10:33 UTC, ekaterinaryzhenkova commented on src/ScheduleService/Controllers/GroupsUsersController.cs
> +      [FromServices] IEditGroupUserCommand command,
fixed

2024-01-24 12:47 UTC, SolovyovDmitry approved these changes

2024-01-24 12:47 UTC, SolovyovDmitry commented on src/ScheduleService.Business/GroupUser/DeleteGroupUserCommand.cs
> +  public DeleteGroupUserCommand(
rename to remove

2024-01-24 12:47 UTC, SolovyovDmitry commented on src/ScheduleService.Models.Dto/Models/GroupUserInfo.cs
> +}
let it be for now but keep in mind it must be reworked later(to have real info from user service instead of just id)

2024-01-27 09:26 UTC, VLiamin approved these changes

2024-01-30 09:45 UTC, merged